### PR TITLE
BUILD-4227 scannerazuresc.json upload

### PR DESCRIPTION
**Pull request by julien-carsique-sonarsource**
Upload scannerazuresc.json to https://downloads.sonarsource.com/?prefix=sonarqube/update

### CODE REVIEW

**Comment by robin-vitre-sonarsource** [comment]
Hey @julien-carsique-sonarsource, thanks for fixing this though I'm not one to review your PR I think, I don't know this project.

**Comment by robin-vitre-sonarsource** [comment]
> Hey @julien-carsique-sonarsource, thanks for fixing this though I'm not one to review your PR I think, I don't know this project. Can you ask anybody else?

@julien-carsique-sonarsource ping

**Comment by kevin-hinz** [comment]
I validate that the [staging result](https://downloads-staging.sonarsource.com/sonarqube/update/scannerazuresc.json) looks correct.

**Review by kevin-hinz — APPROVED** [review]
I validate that the [staging result](https://downloads-staging.sonarsource.com/sonarqube/update/scannerazuresc.json) looks correct. LGTM.

**Pull request merged**
