### PR TITLE
Support SonarQube 9.0 and small fixes

### PR DESCRIPTION
**Pull request by theshadowco**
Support SonarQube 9.0 and small fixes

### CODE REVIEW

**Comment by theshadowco** [comment]
https://community.sonarsource.com/t/new-releases-russian-pack-9-0/47106

**Comment by theshadowco** [comment]
Hmm, how do I know what's broken? 

It's a secret? 
😄 

image

**Review by ganncamp — CHANGES_REQUESTED** [review]
Please remove the plugin versions that target EOL versions of SonarQube, i.e. anything older than 8.9.

**Comment by ganncamp** [comment]
The error message indicates a missing `downloadUrl`. Since they all seem to be there in your PR, my current assumption is that this is caused by another file & I plan to investigate independently of this PR.

**Review by ganncamp — APPROVED** [review]

**Pull request merged**
