### PR TITLE
Update plugins to support sqcb

### PR DESCRIPTION
**Pull request by lukasz-jarocki-sonarsource**
I modified Ann's commits.

### CODE REVIEW

**Comment by lukasz-jarocki-sonarsource** [comment]
Validated locally:
`[INFO] Generate compatibility matrix in: C:\git\sonar-update-center-properties\testinglocally\html\compatibility-matrix.html
[INFO] Generate compatibility matrix in: C:\git\sonar-update-center-properties\testinglocally\html\compatibility-matrix-sqcb.html
`

**Review by christophelevis — APPROVED** [review]
LGTM

**Comment by ganncamp** [comment]
@lukasz-jarocki-sonarsource, @christophelevis @vilchik-elena looking at the live version of this file, it doesn't include compatibility for `sqs`. So we've made this plugin available for SonarQube Community Build, but not our paying customers. Haven't checked any other files...

**Comment by christophelevis** [comment]
@ganncamp We've split the PR into 2 (SQCB and SQS) to fix the plugin version matrix for SQCB while SQS release was pending.
The [PR](https://github.com/SonarSource/sonar-update-center-properties/pull/625) for SQS is now also merged.

**Comment by ganncamp** [comment]
Thanks @christophelevis. I thought y'all had completed the release and left for the day already when I raised this alarm.

**Pull request merged**
