### PR TITLE
remove old SQ versions from public list

### PR DESCRIPTION
**Pull request by ganncamp**

### CODE REVIEW

**Comment by ganncamp** [comment]
@christophelevis, @colin-mueller-sonarsource why haven't we done this already?

**Comment by christophelevis** [comment]
@ganncamp I assume it is part of the effort Colin started with [colin/eol](https://github.com/SonarSource/sonar-update-center-properties/tree/colin/eol) and which is stuck because of the limitation we have on embedded analyzers and editions.
This is a good a first step, and... I would suggest to add to the PR the clean-up of the plugins versions which are no more compatible with SQ <8.9 (like in #208). Happy to help if you want.

**Comment by ganncamp** [comment]
@christophelevis I don't believe #208 can happen until we finally fix the update center to not break without E.G. the Developer plugin. Can we not just do this as a baby step?

**Comment by christophelevis** [comment]
@ganncamp If that works for you, I'll try to go one step further and remove the plugins we already can, reusing partially what Colin initiated.

**Comment by ganncamp** [comment]
Fine for me @christophelevis

**Comment by christophelevis** [comment]
@ganncamp I forgot to ping you but I updated the PR a couple of weeks ago to remove the plugins. Can you please review it?

**Comment by ganncamp** [comment]
Ehm... I think I just (re)did all this last week. See https://discuss.sonarsource.com/t/marketplace-plugin-version-matrix-update-center-update/10471

**Comment by christophelevis** [comment]
ouch... so I guess we can rebase this PR and check if there are differences ;)

**Comment by ganncamp** [comment]
:+1:

**Comment by christophelevis** [comment]
@ganncamp Found a couple of plugin versions to restore and authbitbucket. Please let me know what you think.

**Review by ganncamp — COMMENTED** [review]
Somehow I can't approve this PR, only comment. 
LGTM

**Review by christophelevis — APPROVED** [review]

**Pull request merged**
